import { useEffect, useMemo, useRef, useState } from 'react'
import { useExercises, useFieldTypes } from '../exercises'
import { StorageNotice } from '../../shared/StorageNotice'
import { todayLocal } from '../../shared/localDate'
import { useWorkoutLog } from './useWorkoutLog'
import { useWorkoutSessions } from './useWorkoutSessions'
import { SessionCard } from './SessionCard'
import { SessionForm } from './SessionForm'

const MONTHS=['January','February','March','April','May','June','July','August','September','October','November','December'],WEEKDAYS=['Mon','Tue','Wed','Thu','Fri','Sat','Sun']
function toLocalDateString(year:number,month:number,day:number){return `${year}-${String(month+1).padStart(2,'0')}-${String(day).padStart(2,'0')}`}
export function WorkoutLogPage(){
 const {exercises}=useExercises(),{fieldTypes,allFieldTypes}=useFieldTypes()
 const {sessions,addSession,updateSession,finishSession,error:sessionsError,dismissError:dismissSessionsError}=useWorkoutSessions()
 const {entries,addEntry,updateEntry,deleteEntry,getLastEntry,backfillSessionIds,updateEntriesDate,error:entriesError,dismissError:dismissEntriesError}=useWorkoutLog()
 const [openSessionId,setOpenSessionId]=useState(''),[creating,setCreating]=useState(false),[actionError,setActionError]=useState<string|null>(null),today=todayLocal(),todayDate=new Date(`${today}T12:00:00`),[calendarMonth,setCalendarMonth]=useState(()=>new Date(todayDate.getFullYear(),todayDate.getMonth(),1)),[selectedDate,setSelectedDate]=useState(today),migrated=useRef(false),autoOpened=useRef(false)
 const calendarDays=useMemo(()=>{const y=calendarMonth.getFullYear(),m=calendarMonth.getMonth(),first=new Date(y,m,1),offset=(first.getDay()+6)%7,days=new Date(y,m+1,0).getDate();return Array.from({length:42},(_,i)=>{const d=i-offset+1;return d>=1&&d<=days?d:null})},[calendarMonth])
 const sessionDates=useMemo(()=>new Set(sessions.map(s=>s.date)),[sessions])
 useEffect(()=>{if(migrated.current)return;const legacyDates=[...new Set(entries.filter(e=>!e.sessionId).map(e=>e.date))];if(!legacyDates.length)return;migrated.current=true;const ids:Record<string,string>={};for(const date of legacyDates){const existing=sessions.find(s=>s.date===date&&!s.name);if(existing){ids[date]=existing.id;continue}const created=addSession({date,name:''});if(!created){migrated.current=false;return}ids[date]=created.id}backfillSessionIds(ids)},[entries,sessions,addSession,backfillSessionIds])
 useEffect(()=>{if(autoOpened.current||openSessionId)return;const s=sessions.find(x=>x.date===todayLocal()&&!x.endedAt);if(s){autoOpened.current=true;setOpenSessionId(s.id)}},[sessions,openSessionId])
 function handleCreate(date:string,name:string){autoOpened.current=true;const created=addSession({date,name});if(!created)return false;setActionError(null);setOpenSessionId(created.id);setCreating(false);setSelectedDate(date);return true}
 function handleToggle(id:string){autoOpened.current=true;setOpenSessionId(p=>p===id?'':id)}
 function handleUpdateSession(id:string,date:string,name:string){const s=sessions.find(x=>x.id===id);if(!s)return false;if(!updateSession(id,date,name))return false;if(!updateEntriesDate(id,date)){if(!updateSession(id,s.date,s.name)){setActionError('ERROR: Session and entry dates are now out of sync and both revert attempts failed. Free some storage space and edit the session again to fix.');return false}setActionError('The session was not saved — storage is full. Free some space and try again.');return false}setActionError(null);return true}
 function dismissAll(){dismissSessionsError();dismissEntriesError();setActionError(null)}
 return <section className="workout-log-page target-workout-log"><StorageNotice message={sessionsError??entriesError??actionError} onDismiss={dismissAll}/><header className="workout-log-header"><h2>Workout Log</h2><button type="button" className="workout-log-add" aria-label="New session" onClick={()=>setCreating(v=>!v)}>+</button></header><section className="workout-calendar" aria-label="Workout calendar"><div className="calendar-toolbar"><button type="button" aria-label="Previous month" onClick={()=>setCalendarMonth(c=>new Date(c.getFullYear(),c.getMonth()-1,1))}>‹</button><strong>{MONTHS[calendarMonth.getMonth()]} {calendarMonth.getFullYear()}</strong><button type="button" aria-label="Next month" onClick={()=>setCalendarMonth(c=>new Date(c.getFullYear(),c.getMonth()+1,1))}>›</button></div><div className="calendar-weekdays">{WEEKDAYS.map(d=><span key={d}>{d}</span>)}</div><div className="calendar-grid">{calendarDays.map((day,i)=>{if(!day)return <span key={`empty-${i}`} className="calendar-empty"/>;const date=toLocalDateString(calendarMonth.getFullYear(),calendarMonth.getMonth(),day);return <button key={date} type="button" className={`${selectedDate===date?'selected ':''}${sessionDates.has(date)?'has-workout ':''}${date===today?'today':''}`} onClick={()=>setSelectedDate(date)} aria-label={date}>{day}</button>})}</div></section>{creating&&<div className="editor-panel card"><div className="editor-panel-heading"><h3>Start a session</h3><p>The workout timer starts the moment you start this session.</p></div><SessionForm onSubmit={handleCreate} onCancel={()=>setCreating(false)}/></div>}<div className="workout-log-list-heading"><span>{sessions.length} {sessions.length===1?'workout':'workouts'}</span><button type="button" onClick={()=>setSelectedDate(today)}>Today</button></div>{sessions.length===0&&<div className="empty-state card"><strong>No workouts yet</strong><span>Start your first session and add exercises as you train.</span></div>}{sessions.map(session=><SessionCard key={session.id} session={session} entries={entries.filter(e=>e.sessionId===session.id)} isOpen={session.id===openSessionId} exercises={exercises} fieldTypes={fieldTypes} historyFieldTypes={allFieldTypes} getLastEntry={getLastEntry} onToggle={()=>handleToggle(session.id)} onUpdateSession={(date,name)=>handleUpdateSession(session.id,date,name)} onFinishSession={()=>finishSession(session.id)} onAddEntry={entry=>addEntry({...entry,sessionId:session.id,date:session.date})} onUpdateEntry={updateEntry} onDeleteEntry={deleteEntry}/>)}</section>
}
